import "./globals.css";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import { getCommitHistory, searchRepos } from "./github-api";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

//getCommitHistory({owner: "vercel", name: "next.js"}).then((commits) => console.log({commits}))
//searchRepos("react").then(repos => console.log(JSON.stringify(repos,undefined,2)))

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>{children}</body>
    </html>
  );
}
